import React, { useState, useMemo } from 'react';
import { motion } from 'motion/react';
import { 
  DollarSign, 
  Calendar, 
  TrendingUp, 
  Clock, 
  ArrowUpRight, 
  Search, 
  FileText, 
  BarChart3, 
  ShieldCheck, 
  ArrowRight,
  Filter,
  RefreshCw,
  SlidersHorizontal,
  TrendingDown,
  Building2,
  Package,
  Layers,
  Sparkles,
  Info
} from 'lucide-react';
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer, 
  AreaChart, 
  Area, 
  Legend 
} from 'recharts';
import { InventoryItem, Transmittal, TransmittalItem } from '../types';

interface RevenueDashboardProps {
  inventory: InventoryItem[];
  transmittals: Transmittal[];
}

export default function RevenueDashboard({ inventory, transmittals }: RevenueDashboardProps) {
  // Filters State
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedStatusFilter, setSelectedStatusFilter] = useState('ALL');
  const [selectedStreamFilter, setSelectedStreamFilter] = useState<'ALL' | 'ITEMS' | 'HALLS'>('ALL');
  const [topAssetsCategory, setTopAssetsCategory] = useState<'ALL' | 'ITEMS' | 'HALLS'>('ALL');

  // Quick Date Filters Helper
  const applyQuickDateFilter = (type: 'this-month' | 'last-30' | 'this-year' | 'all') => {
    const today = new Date();
    const yyyy = today.getFullYear();
    const mm = String(today.getMonth() + 1).padStart(2, '0');
    
    if (type === 'this-month') {
      setStartDate(`${yyyy}-${mm}-01`);
      setEndDate(today.toISOString().split('T')[0]);
    } else if (type === 'last-30') {
      const past30 = new Date();
      past30.setDate(today.getDate() - 30);
      setStartDate(past30.toISOString().split('T')[0]);
      setEndDate(today.toISOString().split('T')[0]);
    } else if (type === 'this-year') {
      setStartDate(`${yyyy}-01-01`);
      setEndDate(today.toISOString().split('T')[0]);
    } else {
      setStartDate('');
      setEndDate('');
    }
  };

  // Helper: Detect if an item is a Rental Hall / Event Venue
  const isRentalHallItem = (item: { itemId: string; name: string; sku: string }, invItem?: InventoryItem) => {
    if (invItem?.category === 'Rental Halls & Event Venues') return true;
    if (item.sku && item.sku.toUpperCase().startsWith('HALL-')) return true;
    const nameLower = (item.name || '').toLowerCase();
    if (
      nameLower.includes('hall') || 
      nameLower.includes('ballroom') || 
      nameLower.includes('pavilion') || 
      nameLower.includes('terrace') || 
      nameLower.includes('event venue') ||
      nameLower.includes('function hall')
    ) {
      return true;
    }
    return false;
  };

  // Fallback pricing for legacy or deleted items
  const getFallbackPrice = (name: string): number => {
    const nameLower = (name || '').toLowerCase();
    if (nameLower.includes('photographer') || nameLower.includes('photobooth') || nameLower.includes('corkage') || nameLower.includes('permit')) return 500;
    if (nameLower.includes('chair')) return 35;
    if (nameLower.includes('table')) return 150;
    if (nameLower.includes('plate') || nameLower.includes('bowl') || nameLower.includes('dish')) return 15;
    if (nameLower.includes('glass') || nameLower.includes('cup')) return 20;
    if (nameLower.includes('fork') || nameLower.includes('spoon') || nameLower.includes('knife')) return 10;
    if (nameLower.includes('tent') || nameLower.includes('canopy')) return 1200;
    if (nameLower.includes('sound') || nameLower.includes('speaker') || nameLower.includes('light')) return 800;
    if (nameLower.includes('tray') || nameLower.includes('pan')) return 100;
    if (nameLower.includes('van') || nameLower.includes('car') || nameLower.includes('vehicle')) return 2500;
    return 50;
  };

  // Calculate revenue generated by a single transmittal item
  const calculateItemRevenue = (item: TransmittalItem, dateCheckout: string, dateCheckin: string) => {
    const invItem = inventory.find(i => i.id === item.itemId || (item.sku && i.sku === item.sku));
    const isHall = isRentalHallItem(item, invItem);
    const itemName = item.name || '';

    // 1. Check for day pattern embedded in name: e.g., "Grand Ballroom (2 Day(s) @ ₱18,000/day: ...)"
    const dayMatch = itemName.match(/(\d+)\s*Day\(s\)\s*@\s*₱?([\d,]+)\/day/i);
    if (dayMatch) {
      const days = Math.max(1, parseInt(dayMatch[1], 10) || 1);
      const dailyRate = parseFloat(dayMatch[2].replace(/,/g, '')) || 0;
      const totalItemRevenue = days * dailyRate * (item.quantity || 1);
      return {
        revenue: totalItemRevenue,
        days,
        rate: dailyRate,
        isHourly: false,
        isFlatFee: false,
        isHall: true,
        stream: 'hall' as const,
        rateLabel: `₱${dailyRate.toLocaleString()}/day (${days} day${days > 1 ? 's' : ''})`
      };
    }

    // 2. Check for hour pattern embedded in name: e.g., "Emerald Pavilion (4 hrs @ ₱2,500/hr: ...)"
    const hourMatch = itemName.match(/(\d+)\s*hrs?\s*@\s*₱?([\d,]+)\/hr/i);
    if (hourMatch) {
      const hours = Math.max(1, parseInt(hourMatch[1], 10) || 1);
      const hourlyRate = parseFloat(hourMatch[2].replace(/,/g, '')) || 0;
      const totalItemRevenue = hours * hourlyRate * (item.quantity || 1);
      return {
        revenue: totalItemRevenue,
        days: Math.ceil(hours / 24),
        hours,
        rate: hourlyRate,
        isHourly: true,
        isFlatFee: false,
        isHall,
        stream: (isHall ? 'hall' : 'item') as 'hall' | 'item',
        rateLabel: `₱${hourlyRate.toLocaleString()}/hr (${hours} hr${hours > 1 ? 's' : ''})`
      };
    }

    // 3. Check for flat fee or corkage embedded: e.g., "Outside Catering Permit (₱1,500 fee)"
    const feeMatch = itemName.match(/₱?([\d,]+)\s*(?:fee|flat fee)/i);
    if (feeMatch) {
      const fee = parseFloat(feeMatch[1].replace(/,/g, '')) || 0;
      const totalItemRevenue = fee * (item.quantity || 1);
      return {
        revenue: totalItemRevenue,
        days: 1,
        rate: fee,
        isHourly: false,
        isFlatFee: true,
        isHall,
        stream: (isHall ? 'hall' : 'item') as 'hall' | 'item',
        rateLabel: `₱${fee.toLocaleString()} (flat fee)`
      };
    }

    // 4. Default duration calculation based on transmittal checkout and checkin dates
    const start = new Date(dateCheckout || new Date());
    const end = new Date(dateCheckin || dateCheckout || new Date());
    const diffTime = Math.abs(end.getTime() - start.getTime());
    const days = Math.max(1, Math.ceil(diffTime / (1000 * 60 * 60 * 24))) || 1;

    // If item is classified as a Rental Hall
    if (isHall) {
      const dailyRate = Number(invItem?.dailyRentalPrice) || (invItem?.rentalPrice ? Number(invItem.rentalPrice) * 6 : 18000);
      const totalItemRevenue = dailyRate * days * (item.quantity || 1);
      return {
        revenue: totalItemRevenue,
        days,
        rate: dailyRate,
        isHourly: false,
        isFlatFee: false,
        isHall: true,
        stream: 'hall' as const,
        rateLabel: `₱${dailyRate.toLocaleString()}/day`
      };
    }

    // If item is a flat fee service item
    if (invItem?.isNoQuantity || invItem?.chargeType === 'Flat Fee' || invItem?.category === 'Corkage & Service Permits') {
      const flatRate = Number(invItem?.rentalPrice || 500);
      return {
        revenue: flatRate * (item.quantity || 1),
        days: 1,
        rate: flatRate,
        isHourly: false,
        isFlatFee: true,
        isHall: false,
        stream: 'item' as const,
        rateLabel: `₱${flatRate.toLocaleString()}/flat fee`
      };
    }

    // Standard physical rental asset (Chairs, Tables, Tents, Catering Equipment, Vehicles, etc.)
    const rate = Number(invItem?.dailyRentalPrice || invItem?.rentalPrice || getFallbackPrice(item.name));
    let totalRate = rate;
    if (invItem?.isHourlyCharged) {
      totalRate = rate * 24; // If hourly profile charged per day
    }
    const totalItemRevenue = totalRate * days * (item.quantity || 1);

    return {
      revenue: totalItemRevenue,
      days,
      rate,
      isHourly: !!invItem?.isHourlyCharged,
      isFlatFee: false,
      isHall: false,
      stream: 'item' as const,
      rateLabel: `₱${rate.toLocaleString()}/${invItem?.isHourlyCharged ? 'hr' : 'day'}`
    };
  };

  // Detailed Ledger of all transmittals with computed rental items and rental halls revenue
  const transmittalsWithRevenue = useMemo(() => {
    return transmittals.map(tx => {
      let itemsRevenue = 0;
      let hallsRevenue = 0;

      // 1. Process items
      const itemsDetail = tx.items.map(item => {
        const revCalc = calculateItemRevenue(item, tx.dateCheckout, tx.dateCheckin);
        if (revCalc.stream === 'hall') {
          hallsRevenue += revCalc.revenue;
        } else {
          itemsRevenue += revCalc.revenue;
        }
        return {
          ...item,
          ...revCalc
        };
      });

      // 2. Parse venue rental duration extension surcharges from tx.notes
      // Example format: [EXTENDED +2 HR(S) on Sep 18, 2026, 07:00 PM | +₱5,000]
      let extensionsTotal = 0;
      const extensionLogs: { hours: number; cost: number; raw: string }[] = [];
      if (tx.notes) {
        const extensionRegex = /\[EXTENDED\s*\+(\d+)\s*HR\(S\)[^|]*\|\s*\+₱?([\d,]+)\]/gi;
        let match;
        while ((match = extensionRegex.exec(tx.notes)) !== null) {
          const hours = parseInt(match[1], 10) || 0;
          const cost = parseFloat(match[2].replace(/,/g, '')) || 0;
          extensionsTotal += cost;
          extensionLogs.push({ hours, cost, raw: match[0] });
        }
      }

      // Add extensions revenue to halls revenue
      hallsRevenue += extensionsTotal;
      const totalRevenue = itemsRevenue + hallsRevenue;

      // Classify stream type
      const streamType: 'HALLS' | 'ITEMS' | 'COMBINED' = 
        hallsRevenue > 0 && itemsRevenue > 0
          ? 'COMBINED'
          : hallsRevenue > 0
          ? 'HALLS'
          : 'ITEMS';

      return {
        ...tx,
        itemsRevenue,
        hallsRevenue,
        extensionsTotal,
        extensionLogs,
        totalRevenue,
        streamType,
        itemsDetail
      };
    });
  }, [transmittals, inventory]);

  // Apply filters on transmittals
  const filteredTransmittals = useMemo(() => {
    return transmittalsWithRevenue.filter(tx => {
      // Stream Filter
      if (selectedStreamFilter === 'ITEMS' && tx.itemsRevenue <= 0) return false;
      if (selectedStreamFilter === 'HALLS' && tx.hallsRevenue <= 0) return false;

      // Date Range Filter
      if (startDate && tx.dateCheckout < startDate) return false;
      if (endDate && tx.dateCheckout > endDate) return false;

      // Status Filter
      if (selectedStatusFilter !== 'ALL' && tx.status.toUpperCase() !== selectedStatusFilter) return false;

      // Search Query (AR No, Rentee, Handler, Address, Items)
      if (searchQuery.trim()) {
        const query = searchQuery.toLowerCase();
        const matchesNo = tx.transmittalNo?.toLowerCase().includes(query);
        const matchesRentee = tx.rentee?.toLowerCase().includes(query);
        const matchesHandler = tx.handler?.toLowerCase().includes(query);
        const matchesAddress = tx.address?.toLowerCase().includes(query);
        const matchesItem = tx.items.some(item => item.name.toLowerCase().includes(query));
        if (!matchesNo && !matchesRentee && !matchesHandler && !matchesAddress && !matchesItem) return false;
      }

      return true;
    });
  }, [transmittalsWithRevenue, startDate, endDate, searchQuery, selectedStatusFilter, selectedStreamFilter]);

  // Summary Metrics including Rental Halls & Rental Items revenue
  const metrics = useMemo(() => {
    let totalRevenue = 0;
    let itemsRevenue = 0;
    let hallsRevenue = 0;
    let activeRevenue = 0;
    let completedRevenue = 0;
    let totalContracts = filteredTransmittals.length;
    let totalHallsBookings = 0;
    let totalItemsContracts = 0;

    filteredTransmittals.forEach(tx => {
      totalRevenue += tx.totalRevenue;
      itemsRevenue += tx.itemsRevenue;
      hallsRevenue += tx.hallsRevenue;

      if (tx.hallsRevenue > 0) totalHallsBookings += 1;
      if (tx.itemsRevenue > 0) totalItemsContracts += 1;

      if (tx.status === 'Returned') {
        completedRevenue += tx.totalRevenue;
      } else {
        activeRevenue += tx.totalRevenue;
      }
    });

    const averageRevenue = totalContracts > 0 ? totalRevenue / totalContracts : 0;
    const itemsPercentage = totalRevenue > 0 ? Math.round((itemsRevenue / totalRevenue) * 100) : 0;
    const hallsPercentage = totalRevenue > 0 ? 100 - itemsPercentage : 0;

    return {
      totalRevenue,
      itemsRevenue,
      hallsRevenue,
      activeRevenue,
      completedRevenue,
      averageRevenue,
      totalContracts,
      totalHallsBookings,
      totalItemsContracts,
      itemsPercentage,
      hallsPercentage
    };
  }, [filteredTransmittals]);

  // Top Performing Assets (including Rental Halls and Physical Items)
  const topAssets = useMemo(() => {
    const assetMap: Record<string, { 
      name: string; 
      sku: string; 
      isHall: boolean; 
      qtyRented: number; 
      totalRevenue: number; 
      occurrences: number; 
    }> = {};
    
    filteredTransmittals.forEach(tx => {
      tx.itemsDetail.forEach(item => {
        const isHall = item.isHall;
        if (topAssetsCategory === 'ITEMS' && isHall) return;
        if (topAssetsCategory === 'HALLS' && !isHall) return;

        const assetKey = item.itemId || item.sku || item.name;
        if (!assetMap[assetKey]) {
          assetMap[assetKey] = {
            name: item.name,
            sku: item.sku,
            isHall,
            qtyRented: 0,
            totalRevenue: 0,
            occurrences: 0
          };
        }
        assetMap[assetKey].qtyRented += item.quantity || 1;
        assetMap[assetKey].totalRevenue += item.revenue;
        assetMap[assetKey].occurrences += 1;
      });
    });

    return Object.values(assetMap)
      .sort((a, b) => b.totalRevenue - a.totalRevenue)
      .slice(0, 6);
  }, [filteredTransmittals, topAssetsCategory]);

  // Monthly Breakdown Data for Recharts with Multi-Stream Stacking
  const monthlyData = useMemo(() => {
    const monthMap: Record<string, { 
      monthKey: string; 
      monthLabel: string; 
      itemsRevenue: number; 
      hallsRevenue: number; 
      totalRevenue: number; 
      contracts: number; 
    }> = {};
    
    filteredTransmittals.forEach(tx => {
      if (!tx.dateCheckout) return;
      const [year, month] = tx.dateCheckout.split('-');
      if (!year || !month) return;
      
      const key = `${year}-${month}`;
      const dateObj = new Date(Number(year), Number(month) - 1, 1);
      const label = dateObj.toLocaleDateString('en-US', { month: 'short', year: 'numeric' });

      if (!monthMap[key]) {
        monthMap[key] = {
          monthKey: key,
          monthLabel: label,
          itemsRevenue: 0,
          hallsRevenue: 0,
          totalRevenue: 0,
          contracts: 0
        };
      }
      monthMap[key].itemsRevenue += tx.itemsRevenue;
      monthMap[key].hallsRevenue += tx.hallsRevenue;
      monthMap[key].totalRevenue += tx.totalRevenue;
      monthMap[key].contracts += 1;
    });

    return Object.values(monthMap).sort((a, b) => a.monthKey.localeCompare(b.monthKey));
  }, [filteredTransmittals]);

  // Weekly Breakdown Data for Recharts with Multi-Stream Areas
  const weeklyData = useMemo(() => {
    const weekMap: Record<string, { 
      weekKey: string; 
      weekLabel: string; 
      itemsRevenue: number; 
      hallsRevenue: number; 
      totalRevenue: number; 
      contracts: number; 
    }> = {};
    
    filteredTransmittals.forEach(tx => {
      if (!tx.dateCheckout) return;
      
      const date = new Date(tx.dateCheckout);
      const day = date.getDay();
      const diff = date.getDate() - day + (day === 0 ? -6 : 1);
      const monday = new Date(date.setDate(diff));
      const key = monday.toISOString().split('T')[0];
      const label = monday.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });

      if (!weekMap[key]) {
        weekMap[key] = {
          weekKey: key,
          weekLabel: `Wk of ${label}`,
          itemsRevenue: 0,
          hallsRevenue: 0,
          totalRevenue: 0,
          contracts: 0
        };
      }
      weekMap[key].itemsRevenue += tx.itemsRevenue;
      weekMap[key].hallsRevenue += tx.hallsRevenue;
      weekMap[key].totalRevenue += tx.totalRevenue;
      weekMap[key].contracts += 1;
    });

    return Object.values(weekMap).sort((a, b) => a.weekKey.localeCompare(b.weekKey));
  }, [filteredTransmittals]);

  // Selected Transmittal detail preview state
  const [selectedTxDetail, setSelectedTxDetail] = useState<any | null>(null);

  return (
    <div className="space-y-8">
      {/* Header section */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-zinc-200 pb-6">
        <div>
          <h1 className="text-xl font-black font-display text-zinc-900 uppercase tracking-wider">Rentals Revenue Monitor</h1>
          <p className="text-xs text-zinc-500 mt-1">
            Consolidated financial intelligence for rental properties, physical assets, and rental halls & event venues.
          </p>
        </div>
        
        {/* Quick Date Range Filters */}
        <div className="flex flex-wrap gap-1.5 w-full md:w-auto">
          <button
            onClick={() => applyQuickDateFilter('this-month')}
            className="px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider bg-zinc-50 hover:bg-zinc-100 text-zinc-600 border border-zinc-200 cursor-pointer"
          >
            This Month
          </button>
          <button
            onClick={() => applyQuickDateFilter('last-30')}
            className="px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider bg-zinc-50 hover:bg-zinc-100 text-zinc-600 border border-zinc-200 cursor-pointer"
          >
            Last 30 Days
          </button>
          <button
            onClick={() => applyQuickDateFilter('this-year')}
            className="px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider bg-zinc-50 hover:bg-zinc-100 text-zinc-600 border border-zinc-200 cursor-pointer"
          >
            This Year
          </button>
          <button
            onClick={() => applyQuickDateFilter('all')}
            className="px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider bg-zinc-900 hover:bg-zinc-800 text-white border border-zinc-900 cursor-pointer"
          >
            Reset
          </button>
        </div>
      </div>

      {/* Advanced Filters Drawer/Bar */}
      <div className="bg-zinc-50/70 p-4 border border-zinc-200 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3.5">
        {/* Search */}
        <div className="relative">
          <label className="block text-[9px] font-black text-zinc-400 uppercase tracking-widest mb-1">Search Keywords</label>
          <div className="relative">
            <Search className="absolute left-3 top-2.5 h-3.5 w-3.5 text-zinc-400" />
            <input
              type="text"
              placeholder="Rentee, handler, AR no..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-3 py-1.5 border border-zinc-200 text-xs font-semibold focus:outline-none focus:border-zinc-900 bg-white text-zinc-800"
            />
          </div>
        </div>

        {/* Revenue Stream Filter */}
        <div>
          <label className="block text-[9px] font-black text-zinc-400 uppercase tracking-widest mb-1">Revenue Stream</label>
          <select
            value={selectedStreamFilter}
            onChange={(e) => setSelectedStreamFilter(e.target.value as any)}
            className="w-full px-3 py-1.5 border border-zinc-200 text-xs font-bold focus:outline-none focus:border-zinc-900 bg-white text-zinc-900"
          >
            <option value="ALL">All Streams (Halls + Items)</option>
            <option value="HALLS">Rental Halls & Venues Only</option>
            <option value="ITEMS">Rental Properties & Items Only</option>
          </select>
        </div>

        {/* Start Date */}
        <div>
          <label className="block text-[9px] font-black text-zinc-400 uppercase tracking-widest mb-1">From Date (Checkout)</label>
          <input
            type="date"
            value={startDate}
            onChange={(e) => setStartDate(e.target.value)}
            className="w-full px-3 py-1.5 border border-zinc-200 text-xs font-semibold focus:outline-none focus:border-zinc-900 bg-white text-zinc-800"
          />
        </div>

        {/* End Date */}
        <div>
          <label className="block text-[9px] font-black text-zinc-400 uppercase tracking-widest mb-1">To Date (Checkout)</label>
          <input
            type="date"
            value={endDate}
            onChange={(e) => setEndDate(e.target.value)}
            className="w-full px-3 py-1.5 border border-zinc-200 text-xs font-semibold focus:outline-none focus:border-zinc-900 bg-white text-zinc-800"
          />
        </div>

        {/* Status Filter */}
        <div>
          <label className="block text-[9px] font-black text-zinc-400 uppercase tracking-widest mb-1">Contract Status</label>
          <select
            value={selectedStatusFilter}
            onChange={(e) => setSelectedStatusFilter(e.target.value)}
            className="w-full px-3 py-1.5 border border-zinc-200 text-xs font-semibold focus:outline-none focus:border-zinc-900 bg-white text-zinc-800"
          >
            <option value="ALL">All Statuses</option>
            <option value="ON GOING">Active / On Going</option>
            <option value="RETURNED">Completed / Returned</option>
            <option value="PENDING">Pending Approval</option>
            <option value="PARTIALLY RETURNED">Partially Returned</option>
          </select>
        </div>
      </div>

      {/* Primary Metrics Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
        {/* Total Rentals Revenue */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.2 }}
          className="bg-white border border-zinc-200 p-5 relative overflow-hidden"
        >
          <div className="flex justify-between items-start">
            <div>
              <span className="text-[10px] font-black text-zinc-400 uppercase tracking-widest block mb-1">Total Rentals Revenue</span>
              <h3 className="text-2xl font-extrabold font-display text-zinc-900 tracking-tight">
                ₱{Number(metrics.totalRevenue).toLocaleString()}
              </h3>
            </div>
            <div className="p-2 bg-zinc-900 border border-zinc-800 text-white">
              <DollarSign className="h-4 w-4" />
            </div>
          </div>
          <div className="mt-4 flex items-center justify-between text-[10px] font-bold text-zinc-500 uppercase tracking-wide">
            <span>{metrics.totalContracts} total contracts</span>
            <span className="text-zinc-900 font-mono">100% Volume</span>
          </div>
        </motion.div>

        {/* Rental Halls & Venues Revenue */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.2, delay: 0.05 }}
          className="bg-white border-2 border-emerald-500/40 p-5 relative overflow-hidden bg-emerald-50/10"
        >
          <div className="flex justify-between items-start">
            <div>
              <span className="text-[10px] font-black text-emerald-700 uppercase tracking-widest block mb-1 flex items-center gap-1">
                <Building2 className="h-3 w-3 inline" />
                Rental Halls & Venues
              </span>
              <h3 className="text-2xl font-extrabold font-display text-emerald-800 tracking-tight">
                ₱{Number(metrics.hallsRevenue).toLocaleString()}
              </h3>
            </div>
            <div className="p-2 bg-emerald-50 border border-emerald-200 text-emerald-700">
              <Building2 className="h-4 w-4" />
            </div>
          </div>
          <div className="mt-4 flex items-center justify-between text-[10px] font-bold text-emerald-700 uppercase tracking-wide">
            <span>{metrics.totalHallsBookings} venue bookings</span>
            <span className="font-mono bg-emerald-100/80 px-1.5 py-0.5">{metrics.hallsPercentage}% share</span>
          </div>
        </motion.div>

        {/* Rental Properties & Items Revenue */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.2, delay: 0.1 }}
          className="bg-white border border-zinc-200 p-5 relative overflow-hidden"
        >
          <div className="flex justify-between items-start">
            <div>
              <span className="text-[10px] font-black text-zinc-500 uppercase tracking-widest block mb-1 flex items-center gap-1">
                <Package className="h-3 w-3 inline" />
                Rental Items & Assets
              </span>
              <h3 className="text-2xl font-extrabold font-display text-zinc-900 tracking-tight">
                ₱{Number(metrics.itemsRevenue).toLocaleString()}
              </h3>
            </div>
            <div className="p-2 bg-zinc-100 border border-zinc-200 text-zinc-800">
              <Package className="h-4 w-4" />
            </div>
          </div>
          <div className="mt-4 flex items-center justify-between text-[10px] font-bold text-zinc-500 uppercase tracking-wide">
            <span>{metrics.totalItemsContracts} equipment contracts</span>
            <span className="font-mono bg-zinc-100 px-1.5 py-0.5">{metrics.itemsPercentage}% share</span>
          </div>
        </motion.div>

        {/* Active Accounts Value */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.2, delay: 0.15 }}
          className="bg-white border border-zinc-200 p-5 relative overflow-hidden"
        >
          <div className="flex justify-between items-start">
            <div>
              <span className="text-[10px] font-black text-zinc-400 uppercase tracking-widest block mb-1">Active Accounts Value</span>
              <h3 className="text-2xl font-extrabold font-display text-amber-700 tracking-tight">
                ₱{Number(metrics.activeRevenue).toLocaleString()}
              </h3>
            </div>
            <div className="p-2 bg-amber-50 border border-amber-100 text-amber-600">
              <TrendingUp className="h-4 w-4" />
            </div>
          </div>
          <div className="mt-4 flex items-center justify-between text-[10px] font-bold text-zinc-500 uppercase tracking-wide">
            <span>Collected: ₱{Number(metrics.completedRevenue).toLocaleString()}</span>
            <span className="text-zinc-400">Avg: ₱{Math.round(metrics.averageRevenue).toLocaleString()}</span>
          </div>
        </motion.div>
      </div>

      {/* Revenue Stream Breakdown Summary Bar */}
      <div className="bg-white border border-zinc-200 p-4">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 mb-2">
          <span className="text-[10px] font-black uppercase tracking-widest text-zinc-500 flex items-center gap-1.5">
            <Layers className="h-3.5 w-3.5 text-zinc-700" />
            Revenue Stream Distribution Matrix
          </span>
          <div className="flex items-center gap-4 text-xs font-mono font-bold">
            <span className="flex items-center gap-1.5 text-emerald-700">
              <span className="w-2.5 h-2.5 bg-emerald-600 inline-block"></span>
              Rental Halls: ₱{metrics.hallsRevenue.toLocaleString()} ({metrics.hallsPercentage}%)
            </span>
            <span className="flex items-center gap-1.5 text-zinc-800">
              <span className="w-2.5 h-2.5 bg-zinc-900 inline-block"></span>
              Rental Items: ₱{metrics.itemsRevenue.toLocaleString()} ({metrics.itemsPercentage}%)
            </span>
          </div>
        </div>

        {/* Visual proportional distribution bar */}
        <div className="w-full h-3 bg-zinc-100 flex overflow-hidden border border-zinc-200">
          <div 
            style={{ width: `${metrics.hallsPercentage}%` }} 
            className="bg-emerald-600 h-full transition-all duration-500" 
            title={`Rental Halls: ${metrics.hallsPercentage}%`}
          />
          <div 
            style={{ width: `${metrics.itemsPercentage}%` }} 
            className="bg-zinc-900 h-full transition-all duration-500" 
            title={`Rental Items: ${metrics.itemsPercentage}%`}
          />
        </div>
      </div>

      {/* Charts Section with Consolidated & Multi-Stream Data */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Monthly Breakdown Stacked Bar Chart */}
        <div className="bg-white border border-zinc-200 p-5 flex flex-col h-[360px]">
          <div className="flex justify-between items-center mb-4">
            <div>
              <h3 className="text-[11px] font-black text-zinc-800 uppercase tracking-widest">Monthly Revenue by Stream</h3>
              <p className="text-[9px] text-zinc-400 uppercase tracking-wider font-semibold">Stacked revenue comparing Rental Halls and Items</p>
            </div>
            <div className="text-[10px] font-mono font-bold text-zinc-500 bg-zinc-50 px-2 py-0.5 border border-zinc-100">
              {monthlyData.length} active months
            </div>
          </div>

          <div className="flex-1 w-full text-xs">
            {monthlyData.length === 0 ? (
              <div className="h-full flex flex-col justify-center items-center text-zinc-400 font-bold uppercase tracking-widest text-[10px]">
                No checkout data within range
              </div>
            ) : (
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={monthlyData} margin={{ top: 10, right: 10, left: -10, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f4f4f5" />
                  <XAxis 
                    dataKey="monthLabel" 
                    tickLine={false} 
                    axisLine={false}
                    tick={{ fill: '#71717a', fontSize: 9, fontWeight: 600 }}
                  />
                  <YAxis 
                    tickLine={false} 
                    axisLine={false}
                    tickFormatter={(val) => `₱${val >= 1000 ? (val / 1000) + 'k' : val}`}
                    tick={{ fill: '#71717a', fontSize: 9, fontWeight: 600 }}
                  />
                  <Tooltip 
                    formatter={(value: any, name: any) => [
                      `₱${Number(value).toLocaleString()}`, 
                      name === 'hallsRevenue' ? 'Rental Halls & Venues' : 'Rental Items & Assets'
                    ]}
                    labelStyle={{ fontWeight: 'bold', color: '#18181b', fontSize: '10px' }}
                    contentStyle={{ backgroundColor: '#fff', border: '1px solid #e4e4e7', fontSize: '11px', fontWeight: '600' }}
                  />
                  <Legend 
                    verticalAlign="top" 
                    align="right"
                    wrapperStyle={{ fontSize: '10px', textTransform: 'uppercase', fontWeight: 'bold', paddingBottom: '8px' }}
                    formatter={(val) => val === 'hallsRevenue' ? 'Rental Halls' : 'Rental Items'}
                  />
                  <Bar dataKey="hallsRevenue" stackId="a" fill="#059669" radius={[0, 0, 0, 0]} maxBarSize={40} />
                  <Bar dataKey="itemsRevenue" stackId="a" fill="#18181b" radius={[2, 2, 0, 0]} maxBarSize={40} />
                </BarChart>
              </ResponsiveContainer>
            )}
          </div>
        </div>

        {/* Weekly Breakdown Multi-Area Trend Chart */}
        <div className="bg-white border border-zinc-200 p-5 flex flex-col h-[360px]">
          <div className="flex justify-between items-center mb-4">
            <div>
              <h3 className="text-[11px] font-black text-zinc-800 uppercase tracking-widest">Weekly Revenue Velocity</h3>
              <p className="text-[9px] text-zinc-400 uppercase tracking-wider font-semibold">Weekly aggregate breakdown by stream</p>
            </div>
            <div className="text-[10px] font-mono font-bold text-zinc-500 bg-zinc-50 px-2 py-0.5 border border-zinc-100">
              {weeklyData.length} active weeks
            </div>
          </div>

          <div className="flex-1 w-full text-xs">
            {weeklyData.length === 0 ? (
              <div className="h-full flex flex-col justify-center items-center text-zinc-400 font-bold uppercase tracking-widest text-[10px]">
                No checkout data within range
              </div>
            ) : (
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={weeklyData} margin={{ top: 10, right: 10, left: -10, bottom: 0 }}>
                  <defs>
                    <linearGradient id="colorHalls" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#059669" stopOpacity={0.25}/>
                      <stop offset="95%" stopColor="#059669" stopOpacity={0.0}/>
                    </linearGradient>
                    <linearGradient id="colorItems" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#18181b" stopOpacity={0.2}/>
                      <stop offset="95%" stopColor="#18181b" stopOpacity={0.0}/>
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f4f4f5" />
                  <XAxis 
                    dataKey="weekLabel" 
                    tickLine={false} 
                    axisLine={false}
                    tick={{ fill: '#71717a', fontSize: 9, fontWeight: 600 }}
                  />
                  <YAxis 
                    tickLine={false} 
                    axisLine={false}
                    tickFormatter={(val) => `₱${val >= 1000 ? (val / 1000) + 'k' : val}`}
                    tick={{ fill: '#71717a', fontSize: 9, fontWeight: 600 }}
                  />
                  <Tooltip 
                    formatter={(value: any, name: any) => [
                      `₱${Number(value).toLocaleString()}`, 
                      name === 'hallsRevenue' ? 'Rental Halls' : 'Rental Items'
                    ]}
                    labelStyle={{ fontWeight: 'bold', color: '#18181b', fontSize: '10px' }}
                    contentStyle={{ backgroundColor: '#fff', border: '1px solid #e4e4e7', fontSize: '11px', fontWeight: '600' }}
                  />
                  <Legend 
                    verticalAlign="top" 
                    align="right"
                    wrapperStyle={{ fontSize: '10px', textTransform: 'uppercase', fontWeight: 'bold', paddingBottom: '8px' }}
                    formatter={(val) => val === 'hallsRevenue' ? 'Rental Halls' : 'Rental Items'}
                  />
                  <Area type="monotone" dataKey="hallsRevenue" stroke="#059669" strokeWidth={2} fillOpacity={1} fill="url(#colorHalls)" />
                  <Area type="monotone" dataKey="itemsRevenue" stroke="#18181b" strokeWidth={2} fillOpacity={1} fill="url(#colorItems)" />
                </AreaChart>
              </ResponsiveContainer>
            )}
          </div>
        </div>
      </div>

      {/* Top Assets & Dynamic Calculation Insights */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Top Assets List */}
        <div className="bg-white border border-zinc-200 p-5 lg:col-span-1">
          <div className="border-b border-zinc-100 pb-3 mb-4 flex justify-between items-center">
            <div>
              <h3 className="text-[11px] font-black text-zinc-800 uppercase tracking-widest">Top Performers Matrix</h3>
              <p className="text-[9px] text-zinc-400 uppercase tracking-wider font-bold">Highest rental yield assets</p>
            </div>
            {/* Category Filter for Top Performers */}
            <div className="flex gap-1 text-[9px] font-bold">
              <button
                onClick={() => setTopAssetsCategory('ALL')}
                className={`px-1.5 py-0.5 uppercase cursor-pointer ${
                  topAssetsCategory === 'ALL' 
                    ? 'bg-zinc-900 text-white' 
                    : 'bg-zinc-100 text-zinc-600 hover:bg-zinc-200'
                }`}
              >
                All
              </button>
              <button
                onClick={() => setTopAssetsCategory('HALLS')}
                className={`px-1.5 py-0.5 uppercase cursor-pointer ${
                  topAssetsCategory === 'HALLS' 
                    ? 'bg-emerald-700 text-white' 
                    : 'bg-zinc-100 text-zinc-600 hover:bg-zinc-200'
                }`}
              >
                Halls
              </button>
              <button
                onClick={() => setTopAssetsCategory('ITEMS')}
                className={`px-1.5 py-0.5 uppercase cursor-pointer ${
                  topAssetsCategory === 'ITEMS' 
                    ? 'bg-zinc-900 text-white' 
                    : 'bg-zinc-100 text-zinc-600 hover:bg-zinc-200'
                }`}
              >
                Items
              </button>
            </div>
          </div>

          <div className="space-y-3.5">
            {topAssets.length === 0 ? (
              <p className="text-center py-10 text-[10px] font-bold uppercase tracking-wider text-zinc-400">No rental records in category</p>
            ) : (
              topAssets.map((asset, idx) => (
                <div key={idx} className="flex justify-between items-center border-b border-zinc-50 pb-2.5 last:border-b-0 last:pb-0">
                  <div className="space-y-0.5">
                    <div className="flex items-center gap-1.5">
                      <span className={`inline-block px-1.5 py-0.2 text-[8px] font-black uppercase tracking-wider border ${
                        asset.isHall 
                          ? 'bg-emerald-50 text-emerald-700 border-emerald-200' 
                          : 'bg-zinc-100 text-zinc-700 border-zinc-200'
                      }`}>
                        {asset.isHall ? 'HALL VENUE' : 'RENTAL ITEM'}
                      </span>
                      <p className="text-xs font-bold text-zinc-800 truncate max-w-[150px]">{asset.name}</p>
                    </div>
                    <p className="text-[9px] font-mono text-zinc-400">{asset.sku}</p>
                    <p className="text-[10px] text-zinc-500 font-semibold uppercase tracking-tight">
                      Deployments: <span className="text-zinc-900 font-bold">{asset.qtyRented} units ({asset.occurrences} bookings)</span>
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="text-xs font-mono font-bold text-emerald-800">₱{asset.totalRevenue.toLocaleString()}</p>
                    <p className="text-[9px] font-semibold text-zinc-400 uppercase tracking-widest">Rank #{idx + 1}</p>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Ledger table */}
        <div className="bg-white border border-zinc-200 p-5 lg:col-span-2">
          <div className="border-b border-zinc-100 pb-3 mb-4 flex justify-between items-center">
            <div>
              <h3 className="text-[11px] font-black text-zinc-800 uppercase tracking-widest">Contracts Revenue Ledger</h3>
              <p className="text-[9px] text-zinc-400 uppercase tracking-wider font-bold">Itemized transactional billing records</p>
            </div>
            <div className="text-[10px] font-mono font-bold text-zinc-400 uppercase">
              showing {filteredTransmittals.length} records
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-zinc-200 text-[10px] font-bold uppercase tracking-widest text-zinc-400">
                  <th className="pb-2.5">AR No.</th>
                  <th className="pb-2.5">Stream</th>
                  <th className="pb-2.5">Rentee</th>
                  <th className="pb-2.5">Checkout</th>
                  <th className="pb-2.5 text-right">Hall Rev</th>
                  <th className="pb-2.5 text-right">Item Rev</th>
                  <th className="pb-2.5 text-right">Total Rev</th>
                  <th className="pb-2.5 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-50">
                {filteredTransmittals.length === 0 ? (
                  <tr>
                    <td colSpan={8} className="text-center py-10 text-[10px] font-bold uppercase tracking-wider text-zinc-400">
                      No matching contracts found
                    </td>
                  </tr>
                ) : (
                  filteredTransmittals.map((tx, idx) => (
                    <tr key={idx} className="hover:bg-zinc-50/50 transition-colors">
                      <td className="py-3 text-[11px] font-mono font-bold text-zinc-900">{tx.transmittalNo}</td>
                      <td className="py-3">
                        <span className={`inline-block px-1.5 py-0.5 text-[8px] font-black uppercase tracking-wider border ${
                          tx.streamType === 'HALLS'
                            ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
                            : tx.streamType === 'ITEMS'
                            ? 'bg-zinc-100 text-zinc-700 border-zinc-200'
                            : 'bg-amber-50 text-amber-700 border-amber-200'
                        }`}>
                          {tx.streamType === 'HALLS' ? 'VENUE HALL' : tx.streamType === 'ITEMS' ? 'RENTAL ITEM' : 'COMBINED'}
                        </span>
                      </td>
                      <td className="py-3 text-xs font-semibold text-zinc-800">
                        <div className="truncate max-w-[110px]">{tx.rentee}</div>
                      </td>
                      <td className="py-3 text-[10px] font-mono text-zinc-500 whitespace-nowrap">
                        {tx.dateCheckout.split(' ')[0]}
                      </td>
                      <td className="py-3 text-right text-[11px] font-mono font-bold text-emerald-700">
                        {tx.hallsRevenue > 0 ? `₱${tx.hallsRevenue.toLocaleString()}` : '-'}
                      </td>
                      <td className="py-3 text-right text-[11px] font-mono font-semibold text-zinc-700">
                        {tx.itemsRevenue > 0 ? `₱${tx.itemsRevenue.toLocaleString()}` : '-'}
                      </td>
                      <td className="py-3 text-right text-xs font-mono font-bold text-zinc-900">
                        ₱{tx.totalRevenue.toLocaleString()}
                      </td>
                      <td className="py-3 text-right">
                        <button
                          onClick={() => setSelectedTxDetail(tx)}
                          className="px-2 py-0.5 text-[9px] font-bold uppercase tracking-wider bg-zinc-100 hover:bg-zinc-200 text-zinc-700 cursor-pointer"
                        >
                          Breakdown
                        </button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Invoice Breakdown Modal */}
      {selectedTxDetail && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          {/* Backdrop overlay */}
          <div 
            className="absolute inset-0 bg-zinc-950/45 backdrop-blur-xs" 
            onClick={() => setSelectedTxDetail(null)}
          />

          {/* Modal Container */}
          <div className="bg-white border border-zinc-200 w-full max-w-xl relative z-10 overflow-hidden flex flex-col shadow-2xl">
            {/* Header */}
            <div className="border-b border-zinc-200 p-5 flex justify-between items-center bg-zinc-50/60">
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest block">Detailed Billing Statement</span>
                  <span className={`px-1.5 py-0.2 text-[8px] font-black uppercase tracking-wider border ${
                    selectedTxDetail.streamType === 'HALLS'
                      ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
                      : selectedTxDetail.streamType === 'ITEMS'
                      ? 'bg-zinc-100 text-zinc-700 border-zinc-200'
                      : 'bg-amber-50 text-amber-700 border-amber-200'
                  }`}>
                    {selectedTxDetail.streamType === 'HALLS' ? 'VENUE HALL' : selectedTxDetail.streamType === 'ITEMS' ? 'RENTAL ITEM' : 'COMBINED EVENT'}
                  </span>
                </div>
                <h3 className="text-sm font-black text-zinc-900 uppercase tracking-wide mt-0.5">
                  Invoice Breakdown for {selectedTxDetail.transmittalNo}
                </h3>
              </div>
              <button 
                onClick={() => setSelectedTxDetail(null)}
                className="p-1 hover:bg-zinc-100 text-zinc-400 hover:text-zinc-900 border border-transparent hover:border-zinc-200 cursor-pointer"
              >
                ✕
              </button>
            </div>

            {/* Content */}
            <div className="p-6 space-y-6 overflow-y-auto max-h-[70vh]">
              {/* Rentee Metadata Grid */}
              <div className="grid grid-cols-2 gap-4 bg-zinc-50 p-4 border border-zinc-100 text-[11px]">
                <div>
                  <span className="text-[9px] font-black text-zinc-400 uppercase tracking-widest block">Rentee / Client</span>
                  <p className="font-bold text-zinc-800 mt-0.5">{selectedTxDetail.rentee}</p>
                </div>
                <div>
                  <span className="text-[9px] font-black text-zinc-400 uppercase tracking-widest block">Destination Location</span>
                  <p className="font-semibold text-zinc-600 mt-0.5 truncate">{selectedTxDetail.address || 'Madigun Facilities'}</p>
                </div>
                <div>
                  <span className="text-[9px] font-black text-zinc-400 uppercase tracking-widest block">Checkout Dispatch</span>
                  <p className="font-mono text-zinc-700 mt-0.5">{selectedTxDetail.dateCheckout}</p>
                </div>
                <div>
                  <span className="text-[9px] font-black text-zinc-400 uppercase tracking-widest block">Return Target</span>
                  <p className="font-mono text-zinc-700 mt-0.5">{selectedTxDetail.dateCheckin}</p>
                </div>
              </div>

              {/* Items Statement */}
              <div className="space-y-3">
                <h4 className="text-[10px] font-black text-zinc-400 uppercase tracking-widest border-b border-zinc-100 pb-1 flex justify-between">
                  <span>Contract Line Items</span>
                  <span>Stream</span>
                </h4>
                <div className="divide-y divide-zinc-100">
                  {selectedTxDetail.itemsDetail.map((item: any, idx: number) => (
                    <div key={item.itemId || `${item.sku}-${idx}`} className="py-2.5 flex justify-between items-center text-xs">
                      <div className="space-y-0.5 max-w-[300px]">
                        <div className="flex items-center gap-1.5">
                          <span className={`inline-block px-1.5 py-0.2 text-[8px] font-black uppercase tracking-wider border ${
                            item.stream === 'hall' 
                              ? 'bg-emerald-50 text-emerald-700 border-emerald-200' 
                              : 'bg-zinc-100 text-zinc-700 border-zinc-200'
                          }`}>
                            {item.stream === 'hall' ? 'HALL VENUE' : 'RENTAL ITEM'}
                          </span>
                          <p className="font-bold text-zinc-800">{item.name}</p>
                        </div>
                        <p className="text-[10px] text-zinc-400 font-mono uppercase tracking-wide">{item.sku}</p>
                        <p className="text-[10px] text-zinc-500 font-medium">
                          Billing Rate Basis: <span className="text-zinc-800 font-mono font-bold">{item.rateLabel}</span>
                        </p>
                      </div>
                      <div className="text-right">
                        <p className="font-mono font-bold text-zinc-900">
                          ₱{item.revenue.toLocaleString()}
                        </p>
                        <p className="text-[10px] text-zinc-500 font-semibold">
                          {item.quantity} unit(s)
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Duration Extension Surcharges if applicable */}
              {selectedTxDetail.extensionLogs && selectedTxDetail.extensionLogs.length > 0 && (
                <div className="bg-emerald-50/50 border border-emerald-200 p-3.5 space-y-2">
                  <div className="flex justify-between items-center">
                    <span className="text-[10px] font-black text-emerald-800 uppercase tracking-widest flex items-center gap-1">
                      <Sparkles className="h-3 w-3" />
                      Approved Duration Extension Surcharges
                    </span>
                    <span className="text-xs font-mono font-bold text-emerald-800">
                      +₱{selectedTxDetail.extensionsTotal.toLocaleString()}
                    </span>
                  </div>
                  <div className="space-y-1">
                    {selectedTxDetail.extensionLogs.map((log: any, idx: number) => (
                      <p key={idx} className="text-[11px] text-emerald-900 font-mono bg-white/70 p-1.5 border border-emerald-100">
                        {log.raw}
                      </p>
                    ))}
                  </div>
                </div>
              )}

              {/* Summary Statement */}
              <div className="border-t border-zinc-200 pt-4 space-y-2">
                <div className="flex justify-between text-xs font-semibold text-zinc-600">
                  <span>Rental Halls & Venues Subtotal:</span>
                  <span className="font-mono text-emerald-700 font-bold">₱{selectedTxDetail.hallsRevenue.toLocaleString()}</span>
                </div>
                <div className="flex justify-between text-xs font-semibold text-zinc-600">
                  <span>Rental Properties & Items Subtotal:</span>
                  <span className="font-mono text-zinc-800 font-bold">₱{selectedTxDetail.itemsRevenue.toLocaleString()}</span>
                </div>

                <div className="border-t border-zinc-100 pt-2 flex justify-between items-center">
                  <div>
                    <span className="text-[10px] font-black text-zinc-400 uppercase tracking-widest block">Contract Status</span>
                    <span className={`inline-block px-2 py-0.5 text-[9px] font-black uppercase tracking-widest mt-1 ${
                      selectedTxDetail.status === 'Returned' 
                        ? 'bg-emerald-50 text-emerald-700 border border-emerald-200' 
                        : 'bg-amber-50 text-amber-700 border border-amber-200'
                    }`}>
                      {selectedTxDetail.status}
                    </span>
                  </div>
                  <div className="text-right">
                    <span className="text-[10px] font-black text-zinc-400 uppercase tracking-widest block">Total Consolidated Invoice</span>
                    <span className="text-xl font-black font-mono text-zinc-900 mt-0.5 block">
                      ₱{selectedTxDetail.totalRevenue.toLocaleString()}
                    </span>
                  </div>
                </div>
              </div>
            </div>

            {/* Footer */}
            <div className="border-t border-zinc-200 p-4 bg-zinc-50/50 flex justify-end">
              <button
                onClick={() => setSelectedTxDetail(null)}
                className="px-4 py-1.5 text-xs font-bold uppercase tracking-widest text-zinc-800 bg-white border border-zinc-300 hover:bg-zinc-100 transition-colors cursor-pointer"
              >
                Close Statement
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
