import React, { useState, useMemo } from 'react';
import { motion } from 'motion/react';
import { 
  DollarSign, 
  Calendar, 
  TrendingUp, 
  Clock, 
  ArrowUpRight, 
  Search, 
  FileText, 
  BarChart3, 
  ShieldCheck, 
  ArrowRight,
  Filter,
  RefreshCw,
  SlidersHorizontal,
  TrendingDown
} from 'lucide-react';
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer, 
  LineChart, 
  Line, 
  AreaChart, 
  Area, 
  Legend 
} from 'recharts';
import { InventoryItem, Transmittal, TransmittalItem } from '../types';

interface RevenueDashboardProps {
  inventory: InventoryItem[];
  transmittals: Transmittal[];
}

export default function RevenueDashboard({ inventory, transmittals }: RevenueDashboardProps) {
  // Filters State
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedStatusFilter, setSelectedStatusFilter] = useState('ALL');

  // Quick Date Filters Helper
  const applyQuickDateFilter = (type: 'this-month' | 'last-30' | 'this-year' | 'all') => {
    const today = new Date();
    const yyyy = today.getFullYear();
    const mm = String(today.getMonth() + 1).padStart(2, '0');
    
    if (type === 'this-month') {
      setStartDate(`${yyyy}-${mm}-01`);
      setEndDate(today.toISOString().split('T')[0]);
    } else if (type === 'last-30') {
      const past30 = new Date();
      past30.setDate(today.getDate() - 30);
      setStartDate(past30.toISOString().split('T')[0]);
      setEndDate(today.toISOString().split('T')[0]);
    } else if (type === 'this-year') {
      setStartDate(`${yyyy}-01-01`);
      setEndDate(today.toISOString().split('T')[0]);
    } else {
      setStartDate('');
      setEndDate('');
    }
  };

  // Helper: Retrieve rental rate info with robust fallbacks for legacy/deleted items
  const getRentalRate = (item: { itemId: string; name: string; sku: string }) => {
    const invItem = inventory.find(i => i.id === item.itemId);
    if (invItem) {
      const isNoQty = !!invItem.isNoQuantity || invItem.category === 'Corkage & Service Permits';
      return {
        rate: Number(invItem.rentalPrice || 0),
        isHourly: !!invItem.isHourlyCharged,
        isNoQuantity: isNoQty,
        chargeType: invItem.chargeType || (isNoQty ? 'Flat Fee' : 'Daily'),
        name: invItem.name,
        sku: invItem.sku || item.sku
      };
    }

    // Dynamic price estimation fallback for deleted/legacy items so history stays complete
    let price = 50; 
    const nameLower = item.name.toLowerCase();
    let isNoQtyFallback = false;
    if (nameLower.includes('photographer') || nameLower.includes('photobooth') || nameLower.includes('corkage') || nameLower.includes('permit')) {
      price = 500;
      isNoQtyFallback = true;
    } else if (nameLower.includes('chair')) price = 35;
    else if (nameLower.includes('table')) price = 150;
    else if (nameLower.includes('plate') || nameLower.includes('bowl') || nameLower.includes('dish')) price = 15;
    else if (nameLower.includes('glass') || nameLower.includes('cup')) price = 20;
    else if (nameLower.includes('fork') || nameLower.includes('spoon') || nameLower.includes('knife')) price = 10;
    else if (nameLower.includes('tent') || nameLower.includes('canopy')) price = 1200;
    else if (nameLower.includes('sound') || nameLower.includes('speaker') || nameLower.includes('light')) price = 800;
    else if (nameLower.includes('tray') || nameLower.includes('pan')) price = 100;

    return {
      rate: price,
      isHourly: false,
      isNoQuantity: isNoQtyFallback,
      chargeType: isNoQtyFallback ? 'Flat Fee' : 'Daily',
      name: item.name,
      sku: item.sku
    };
  };

  // Helper: Calculate revenue generated by a single transmittal item
  const calculateItemRevenue = (item: TransmittalItem, dateCheckout: string, dateCheckin: string) => {
    const rateInfo = getRentalRate(item);
    
    // Parse dates to compute duration
    const start = new Date(dateCheckout || new Date());
    const end = new Date(dateCheckin || dateCheckout || new Date());
    
    // Calculate duration in days (minimum 1 day)
    const diffTime = Math.abs(end.getTime() - start.getTime());
    const days = Math.max(1, Math.ceil(diffTime / (1000 * 60 * 60 * 24))) || 1;
    
    // Check if flat fee corkage item
    if (rateInfo.isNoQuantity || rateInfo.chargeType === 'Flat Fee') {
      const totalItemRevenue = rateInfo.rate * item.quantity;
      return {
        revenue: totalItemRevenue,
        days,
        rate: rateInfo.rate,
        isHourly: false,
        isFlatFee: true,
        rateLabel: `₱${rateInfo.rate}/flat fee`
      };
    }

    let totalRate = rateInfo.rate;
    if (rateInfo.isHourly) {
      // If hourly, assume standard 24 hours per day
      totalRate = rateInfo.rate * 24;
    }

    const totalItemRevenue = totalRate * days * item.quantity;
    return {
      revenue: totalItemRevenue,
      days,
      rate: rateInfo.rate,
      isHourly: rateInfo.isHourly,
      isFlatFee: false,
      rateLabel: `₱${rateInfo.rate}/${rateInfo.isHourly ? 'hr' : 'day'}`
    };
  };

  // Detailed Ledger of all transmittals with computed revenue
  const transmittalsWithRevenue = useMemo(() => {
    return transmittals.map(tx => {
      let totalRevenue = 0;
      const itemsDetail = tx.items.map(item => {
        const revCalc = calculateItemRevenue(item, tx.dateCheckout, tx.dateCheckin);
        totalRevenue += revCalc.revenue;
        return {
          ...item,
          ...revCalc
        };
      });

      return {
        ...tx,
        totalRevenue,
        itemsDetail
      };
    });
  }, [transmittals, inventory]);

  // Apply filters on transmittals
  const filteredTransmittals = useMemo(() => {
    return transmittalsWithRevenue.filter(tx => {
      // Date Range Filter
      if (startDate && tx.dateCheckout < startDate) return false;
      if (endDate && tx.dateCheckout > endDate) return false;

      // Status Filter
      if (selectedStatusFilter !== 'ALL' && tx.status.toUpperCase() !== selectedStatusFilter) return false;

      // Search Query (No, Rentee, Handler, Address)
      if (searchQuery.trim()) {
        const query = searchQuery.toLowerCase();
        const matchesNo = tx.transmittalNo?.toLowerCase().includes(query);
        const matchesRentee = tx.rentee?.toLowerCase().includes(query);
        const matchesHandler = tx.handler?.toLowerCase().includes(query);
        const matchesAddress = tx.address?.toLowerCase().includes(query);
        const matchesItem = tx.items.some(item => item.name.toLowerCase().includes(query));
        if (!matchesNo && !matchesRentee && !matchesHandler && !matchesAddress && !matchesItem) return false;
      }

      return true;
    });
  }, [transmittalsWithRevenue, startDate, endDate, searchQuery, selectedStatusFilter]);

  // Summary Metrics
  const metrics = useMemo(() => {
    let totalRevenue = 0;
    let activeRevenue = 0;
    let completedRevenue = 0;
    let totalContracts = filteredTransmittals.length;

    filteredTransmittals.forEach(tx => {
      totalRevenue += tx.totalRevenue;
      if (tx.status === 'Returned') {
        completedRevenue += tx.totalRevenue;
      } else {
        activeRevenue += tx.totalRevenue;
      }
    });

    const averageRevenue = totalContracts > 0 ? totalRevenue / totalContracts : 0;

    return {
      totalRevenue,
      activeRevenue,
      completedRevenue,
      averageRevenue,
      totalContracts
    };
  }, [filteredTransmittals]);

  // Top Performing Assets
  const topAssets = useMemo(() => {
    const assetMap: Record<string, { name: string; sku: string; qtyRented: number; totalRevenue: number; occurrences: number }> = {};
    
    filteredTransmittals.forEach(tx => {
      tx.itemsDetail.forEach(item => {
        if (!assetMap[item.itemId]) {
          assetMap[item.itemId] = {
            name: item.name,
            sku: item.sku,
            qtyRented: 0,
            totalRevenue: 0,
            occurrences: 0
          };
        }
        assetMap[item.itemId].qtyRented += item.quantity;
        assetMap[item.itemId].totalRevenue += item.revenue;
        assetMap[item.itemId].occurrences += 1;
      });
    });

    return Object.values(assetMap)
      .sort((a, b) => b.totalRevenue - a.totalRevenue)
      .slice(0, 5);
  }, [filteredTransmittals]);

  // Monthly Breakdown Data for Recharts
  const monthlyData = useMemo(() => {
    const monthMap: Record<string, { monthKey: string; monthLabel: string; revenue: number; contracts: number }> = {};
    
    filteredTransmittals.forEach(tx => {
      if (!tx.dateCheckout) return;
      const [year, month] = tx.dateCheckout.split('-');
      if (!year || !month) return;
      
      const key = `${year}-${month}`;
      const dateObj = new Date(Number(year), Number(month) - 1, 1);
      const label = dateObj.toLocaleDateString('en-US', { month: 'short', year: 'numeric' });

      if (!monthMap[key]) {
        monthMap[key] = {
          monthKey: key,
          monthLabel: label,
          revenue: 0,
          contracts: 0
        };
      }
      monthMap[key].revenue += tx.totalRevenue;
      monthMap[key].contracts += 1;
    });

    return Object.values(monthMap).sort((a, b) => a.monthKey.localeCompare(b.monthKey));
  }, [filteredTransmittals]);

  // Weekly Breakdown Data for Recharts
  const weeklyData = useMemo(() => {
    const weekMap: Record<string, { weekKey: string; weekLabel: string; revenue: number; contracts: number }> = {};
    
    filteredTransmittals.forEach(tx => {
      if (!tx.dateCheckout) return;
      
      // Get start of the week (Monday)
      const date = new Date(tx.dateCheckout);
      const day = date.getDay();
      const diff = date.getDate() - day + (day === 0 ? -6 : 1);
      const monday = new Date(date.setDate(diff));
      const key = monday.toISOString().split('T')[0];
      const label = monday.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });

      if (!weekMap[key]) {
        weekMap[key] = {
          weekKey: key,
          weekLabel: `Wk of ${label}`,
          revenue: 0,
          contracts: 0
        };
      }
      weekMap[key].revenue += tx.totalRevenue;
      weekMap[key].contracts += 1;
    });

    return Object.values(weekMap).sort((a, b) => a.weekKey.localeCompare(b.weekKey));
  }, [filteredTransmittals]);

  // Selected Transmittal detail preview state
  const [selectedTxDetail, setSelectedTxDetail] = useState<any | null>(null);

  return (
    <div className="space-y-8">
      {/* Header section */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-zinc-200 pb-6">
        <div>
          <h1 className="text-xl font-black font-display text-zinc-900 uppercase tracking-wider">Rentals Revenue Monitor</h1>
        </div>
        
        {/* Quick Date Range Filters */}
        <div className="flex flex-wrap gap-1.5 w-full md:w-auto">
          <button
            onClick={() => applyQuickDateFilter('this-month')}
            className="px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider bg-zinc-50 hover:bg-zinc-100 text-zinc-600 border border-zinc-200"
          >
            This Month
          </button>
          <button
            onClick={() => applyQuickDateFilter('last-30')}
            className="px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider bg-zinc-50 hover:bg-zinc-100 text-zinc-600 border border-zinc-200"
          >
            Last 30 Days
          </button>
          <button
            onClick={() => applyQuickDateFilter('this-year')}
            className="px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider bg-zinc-50 hover:bg-zinc-100 text-zinc-600 border border-zinc-200"
          >
            This Year
          </button>
          <button
            onClick={() => applyQuickDateFilter('all')}
            className="px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider bg-zinc-900 hover:bg-zinc-800 text-white border border-zinc-900"
          >
            Reset
          </button>
        </div>
      </div>

      {/* Advanced Filters Drawer/Bar */}
      <div className="bg-zinc-50/55 p-4 border border-zinc-200 grid grid-cols-1 md:grid-cols-4 gap-4">
        {/* Search */}
        <div className="relative">
          <label className="block text-[9px] font-black text-zinc-400 uppercase tracking-widest mb-1">Search Keywords</label>
          <div className="relative">
            <Search className="absolute left-3 top-2.5 h-3.5 w-3.5 text-zinc-400" />
            <input
              type="text"
              placeholder="Rentee, handler, tx no..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-3 py-1.5 border border-zinc-200 text-xs font-semibold focus:outline-none focus:border-zinc-900 bg-white text-zinc-800"
            />
          </div>
        </div>

        {/* Start Date */}
        <div>
          <label className="block text-[9px] font-black text-zinc-400 uppercase tracking-widest mb-1">From Date (Checkout)</label>
          <input
            type="date"
            value={startDate}
            onChange={(e) => setStartDate(e.target.value)}
            className="w-full px-3 py-1.5 border border-zinc-200 text-xs font-semibold focus:outline-none focus:border-zinc-900 bg-white text-zinc-800"
          />
        </div>

        {/* End Date */}
        <div>
          <label className="block text-[9px] font-black text-zinc-400 uppercase tracking-widest mb-1">To Date (Checkout)</label>
          <input
            type="date"
            value={endDate}
            onChange={(e) => setEndDate(e.target.value)}
            className="w-full px-3 py-1.5 border border-zinc-200 text-xs font-semibold focus:outline-none focus:border-zinc-900 bg-white text-zinc-800"
          />
        </div>

        {/* Status Filter */}
        <div>
          <label className="block text-[9px] font-black text-zinc-400 uppercase tracking-widest mb-1">Contract Status</label>
          <select
            value={selectedStatusFilter}
            onChange={(e) => setSelectedStatusFilter(e.target.value)}
            className="w-full px-3 py-1.5 border border-zinc-200 text-xs font-semibold focus:outline-none focus:border-zinc-900 bg-white text-zinc-800"
          >
            <option value="ALL">All Statuses</option>
            <option value="ON GOING">Active / On Going</option>
            <option value="RETURNED">Completed / Returned</option>
            <option value="PENDING">Pending Approval</option>
            <option value="PARTIALLY RETURNED">Partially Returned</option>
          </select>
        </div>
      </div>

      {/* Metrics Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
        {/* Metric 1 */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.2 }}
          className="bg-white border border-zinc-200 p-5 relative overflow-hidden"
        >
          <div className="flex justify-between items-start">
            <div>
              <span className="text-[10px] font-black text-zinc-400 uppercase tracking-widest block mb-1">Total Rent Revenue</span>
              <h3 className="text-2xl font-extrabold font-display text-zinc-900 tracking-tight">
                ₱{Number(metrics.totalRevenue).toLocaleString()}
              </h3>
            </div>
            <div className="p-2 bg-emerald-50 border border-emerald-100 text-emerald-700">
              <DollarSign className="h-4 w-4" />
            </div>
          </div>
          <div className="mt-4 flex items-center text-[10px] font-bold text-zinc-500 uppercase tracking-wide">
            <span className="text-zinc-400 mr-1">Based on</span>
            <span className="text-zinc-800">{metrics.totalContracts} filter contracts</span>
          </div>
        </motion.div>

        {/* Metric 2 */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.2, delay: 0.05 }}
          className="bg-white border border-zinc-200 p-5 relative overflow-hidden"
        >
          <div className="flex justify-between items-start">
            <div>
              <span className="text-[10px] font-black text-zinc-400 uppercase tracking-widest block mb-1">Active Accounts Value</span>
              <h3 className="text-2xl font-extrabold font-display text-zinc-900 tracking-tight">
                ₱{Number(metrics.activeRevenue).toLocaleString()}
              </h3>
            </div>
            <div className="p-2 bg-amber-50 border border-amber-100 text-amber-600">
              <TrendingUp className="h-4 w-4" />
            </div>
          </div>
          <div className="mt-4 flex items-center text-[10px] font-bold text-zinc-500 uppercase tracking-wide">
            <span className="text-zinc-400 mr-1">Deployed assets value out</span>
          </div>
        </motion.div>

        {/* Metric 3 */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.2, delay: 0.1 }}
          className="bg-white border border-zinc-200 p-5 relative overflow-hidden"
        >
          <div className="flex justify-between items-start">
            <div>
              <span className="text-[10px] font-black text-zinc-400 uppercase tracking-widest block mb-1">Collected Revenue</span>
              <h3 className="text-2xl font-extrabold font-display text-emerald-800 tracking-tight">
                ₱{Number(metrics.completedRevenue).toLocaleString()}
              </h3>
            </div>
            <div className="p-2 bg-emerald-50 border border-emerald-100 text-emerald-700">
              <ShieldCheck className="h-4 w-4" />
            </div>
          </div>
          <div className="mt-4 flex items-center text-[10px] font-bold text-zinc-500 uppercase tracking-wide">
            <span className="text-zinc-400 mr-1">Fully closed & returned contracts</span>
          </div>
        </motion.div>

        {/* Metric 4 */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.2, delay: 0.15 }}
          className="bg-white border border-zinc-200 p-5 relative overflow-hidden"
        >
          <div className="flex justify-between items-start">
            <div>
              <span className="text-[10px] font-black text-zinc-400 uppercase tracking-widest block mb-1">Average Order Value</span>
              <h3 className="text-2xl font-extrabold font-display text-zinc-900 tracking-tight">
                ₱{Number(Math.round(metrics.averageRevenue)).toLocaleString()}
              </h3>
            </div>
            <div className="p-2 bg-zinc-50 border border-zinc-200 text-zinc-700">
              <BarChart3 className="h-4 w-4" />
            </div>
          </div>
          <div className="mt-4 flex items-center text-[10px] font-bold text-zinc-500 uppercase tracking-wide">
            <span className="text-zinc-400 mr-1">Mean revenue per transaction</span>
          </div>
        </motion.div>
      </div>

      {/* Charts Section */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Monthly Breakdown Chart */}
        <div className="bg-white border border-zinc-200 p-5 flex flex-col h-[340px]">
          <div className="flex justify-between items-center mb-4">
            <div>
              <h3 className="text-[11px] font-black text-zinc-800 uppercase tracking-widest">Monthly Revenue Overview</h3>
              <p className="text-[9px] text-zinc-400 uppercase tracking-wider font-semibold">Consolidated billing records by month</p>
            </div>
            <div className="text-[10px] font-mono font-bold text-zinc-500 bg-zinc-50 px-2 py-0.5 border border-zinc-100">
              {monthlyData.length} active months
            </div>
          </div>

          <div className="flex-1 w-full text-xs">
            {monthlyData.length === 0 ? (
              <div className="h-full flex flex-col justify-center items-center text-zinc-400 font-bold uppercase tracking-widest text-[10px]">
                No checkout data within range
              </div>
            ) : (
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={monthlyData} margin={{ top: 10, right: 10, left: -10, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f4f4f5" />
                  <XAxis 
                    dataKey="monthLabel" 
                    tickLine={false} 
                    axisLine={false}
                    tick={{ fill: '#71717a', fontSize: 9, fontWeight: 600 }}
                  />
                  <YAxis 
                    tickLine={false} 
                    axisLine={false}
                    tickFormatter={(val) => `₱${val >= 1000 ? (val / 1000) + 'k' : val}`}
                    tick={{ fill: '#71717a', fontSize: 9, fontWeight: 600 }}
                  />
                  <Tooltip 
                    formatter={(value) => [`₱${Number(value).toLocaleString()}`, 'Revenue']}
                    labelStyle={{ fontWeight: 'bold', color: '#18181b', fontSize: '10px' }}
                    contentStyle={{ backgroundColor: '#fff', border: '1px solid #e4e4e7', fontSize: '11px', fontWeight: 'semibold' }}
                  />
                  <Bar dataKey="revenue" fill="#18181b" radius={[2, 2, 0, 0]} maxBarSize={40} />
                </BarChart>
              </ResponsiveContainer>
            )}
          </div>
        </div>

        {/* Weekly Breakdown Chart */}
        <div className="bg-white border border-zinc-200 p-5 flex flex-col h-[340px]">
          <div className="flex justify-between items-center mb-4">
            <div>
              <h3 className="text-[11px] font-black text-zinc-800 uppercase tracking-widest">Weekly Revenue Trend</h3>
              <p className="text-[9px] text-zinc-400 uppercase tracking-wider font-semibold">Revenue aggregation grouped by week of dispatch</p>
            </div>
            <div className="text-[10px] font-mono font-bold text-zinc-500 bg-zinc-50 px-2 py-0.5 border border-zinc-100">
              {weeklyData.length} active weeks
            </div>
          </div>

          <div className="flex-1 w-full text-xs">
            {weeklyData.length === 0 ? (
              <div className="h-full flex flex-col justify-center items-center text-zinc-400 font-bold uppercase tracking-widest text-[10px]">
                No checkout data within range
              </div>
            ) : (
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={weeklyData} margin={{ top: 10, right: 10, left: -10, bottom: 0 }}>
                  <defs>
                    <linearGradient id="colorRevenue" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#18181b" stopOpacity={0.15}/>
                      <stop offset="95%" stopColor="#18181b" stopOpacity={0.0}/>
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f4f4f5" />
                  <XAxis 
                    dataKey="weekLabel" 
                    tickLine={false} 
                    axisLine={false}
                    tick={{ fill: '#71717a', fontSize: 9, fontWeight: 600 }}
                  />
                  <YAxis 
                    tickLine={false} 
                    axisLine={false}
                    tickFormatter={(val) => `₱${val >= 1000 ? (val / 1000) + 'k' : val}`}
                    tick={{ fill: '#71717a', fontSize: 9, fontWeight: 600 }}
                  />
                  <Tooltip 
                    formatter={(value) => [`₱${Number(value).toLocaleString()}`, 'Weekly Revenue']}
                    labelStyle={{ fontWeight: 'bold', color: '#18181b', fontSize: '10px' }}
                    contentStyle={{ backgroundColor: '#fff', border: '1px solid #e4e4e7', fontSize: '11px', fontWeight: 'semibold' }}
                  />
                  <Area type="monotone" dataKey="revenue" stroke="#18181b" strokeWidth={2} fillOpacity={1} fill="url(#colorRevenue)" />
                </AreaChart>
              </ResponsiveContainer>
            )}
          </div>
        </div>
      </div>

      {/* Top Assets & Dynamic Calculation Insights */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Top Assets List */}
        <div className="bg-white border border-zinc-200 p-5 lg:col-span-1">
          <div className="border-b border-zinc-100 pb-3 mb-4">
            <h3 className="text-[11px] font-black text-zinc-800 uppercase tracking-widest">Top Performers Matrix</h3>
            <p className="text-[9px] text-zinc-400 uppercase tracking-wider font-bold">Highest rental yield assets</p>
          </div>

          <div className="space-y-4">
            {topAssets.length === 0 ? (
              <p className="text-center py-10 text-[10px] font-bold uppercase tracking-wider text-zinc-400">No rental history registered</p>
            ) : (
              topAssets.map((asset, idx) => (
                <div key={idx} className="flex justify-between items-center border-b border-zinc-50 pb-3 last:border-b-0 last:pb-0">
                  <div className="space-y-0.5">
                    <p className="text-xs font-bold text-zinc-800 truncate max-w-[160px]">{asset.name}</p>
                    <p className="text-[9px] font-mono text-zinc-400">{asset.sku}</p>
                    <p className="text-[10px] text-zinc-500 font-semibold uppercase tracking-tight">
                      Rented: <span className="text-zinc-900 font-bold">{asset.qtyRented} units</span>
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="text-xs font-mono font-bold text-emerald-800">₱{asset.totalRevenue.toLocaleString()}</p>
                    <p className="text-[9px] font-semibold text-zinc-400 uppercase tracking-widest">Index #{idx + 1}</p>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Ledger table */}
        <div className="bg-white border border-zinc-200 p-5 lg:col-span-2">
          <div className="border-b border-zinc-100 pb-3 mb-4 flex justify-between items-center">
            <div>
              <h3 className="text-[11px] font-black text-zinc-800 uppercase tracking-widest">Contracts Revenue Ledger</h3>
              <p className="text-[9px] text-zinc-400 uppercase tracking-wider font-bold">Itemized transactional billing records</p>
            </div>
            <div className="text-[10px] font-mono font-bold text-zinc-400 uppercase">
              showing {filteredTransmittals.length} records
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-zinc-200 text-[10px] font-bold uppercase tracking-widest text-zinc-400">
                  <th className="pb-2.5">Tx No.</th>
                  <th className="pb-2.5">Rentee</th>
                  <th className="pb-2.5">Checkout</th>
                  <th className="pb-2.5">Days</th>
                  <th className="pb-2.5 text-right">Revenue</th>
                  <th className="pb-2.5 text-right">Details</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-50">
                {filteredTransmittals.length === 0 ? (
                  <tr>
                    <td colSpan={6} className="text-center py-10 text-[10px] font-bold uppercase tracking-wider text-zinc-400">
                      No matching contracts found
                    </td>
                  </tr>
                ) : (
                  filteredTransmittals.map((tx, idx) => (
                    <tr key={idx} className="hover:bg-zinc-50/50 transition-colors">
                      <td className="py-3 text-[11px] font-mono font-bold text-zinc-900">{tx.transmittalNo}</td>
                      <td className="py-3 text-xs font-semibold text-zinc-800">
                        <div className="truncate max-w-[120px]">{tx.rentee}</div>
                      </td>
                      <td className="py-3 text-[11px] font-mono text-zinc-500">{tx.dateCheckout}</td>
                      <td className="py-3 text-xs font-bold text-zinc-600">
                        {/* Calculate simple checkout duration */}
                        {Math.max(1, Math.ceil(Math.abs(new Date(tx.dateCheckin).getTime() - new Date(tx.dateCheckout).getTime()) / (1000 * 60 * 60 * 24)))}
                      </td>
                      <td className="py-3 text-right text-xs font-mono font-bold text-zinc-900">
                        ₱{tx.totalRevenue.toLocaleString()}
                      </td>
                      <td className="py-3 text-right">
                        <button
                          onClick={() => setSelectedTxDetail(tx)}
                          className="px-2 py-0.5 text-[9px] font-bold uppercase tracking-wider bg-zinc-100 hover:bg-zinc-200 text-zinc-700 cursor-pointer"
                        >
                          Invoice Breakdown
                        </button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Invoice Breakdown Modal */}
      {selectedTxDetail && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          {/* Backdrop overlay */}
          <div 
            className="absolute inset-0 bg-zinc-950/45 backdrop-blur-xs" 
            onClick={() => setSelectedTxDetail(null)}
          />

          {/* Modal Container */}
          <div className="bg-white border border-zinc-200 w-full max-w-xl relative z-10 overflow-hidden flex flex-col shadow-2xl">
            {/* Header */}
            <div className="border-b border-zinc-200 p-5 flex justify-between items-center bg-zinc-50/60">
              <div>
                <span className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest block">Detailed Billing Statement</span>
                <h3 className="text-sm font-black text-zinc-900 uppercase tracking-wide mt-0.5">
                  Invoice Breakdown for {selectedTxDetail.transmittalNo}
                </h3>
              </div>
              <button 
                onClick={() => setSelectedTxDetail(null)}
                className="p-1 hover:bg-zinc-100 text-zinc-400 hover:text-zinc-900 border border-transparent hover:border-zinc-200"
              >
                ✕
              </button>
            </div>

            {/* Content */}
            <div className="p-6 space-y-6 overflow-y-auto max-h-[70vh]">
              {/* Rentee Metadata Grid */}
              <div className="grid grid-cols-2 gap-4 bg-zinc-50 p-4 border border-zinc-100 text-[11px]">
                <div>
                  <span className="text-[9px] font-black text-zinc-400 uppercase tracking-widest block">Rentee / Event</span>
                  <p className="font-bold text-zinc-800 mt-0.5">{selectedTxDetail.rentee}</p>
                </div>
                <div>
                  <span className="text-[9px] font-black text-zinc-400 uppercase tracking-widest block">Destination Location</span>
                  <p className="font-semibold text-zinc-600 mt-0.5 truncate">{selectedTxDetail.address}</p>
                </div>
                <div>
                  <span className="text-[9px] font-black text-zinc-400 uppercase tracking-widest block">Checkout Dispatch</span>
                  <p className="font-mono text-zinc-700 mt-0.5">{selectedTxDetail.dateCheckout}</p>
                </div>
                <div>
                  <span className="text-[9px] font-black text-zinc-400 uppercase tracking-widest block">Return Target</span>
                  <p className="font-mono text-zinc-700 mt-0.5">{selectedTxDetail.dateCheckin}</p>
                </div>
              </div>

              {/* Items Statement */}
              <div className="space-y-3">
                <h4 className="text-[10px] font-black text-zinc-400 uppercase tracking-widest border-b border-zinc-100 pb-1">Rent Items Breakdown</h4>
                <div className="divide-y divide-zinc-100">
                  {selectedTxDetail.itemsDetail.map((item: any, idx: number) => (
                    <div key={item.itemId || `${item.sku}-${idx}`} className="py-2.5 flex justify-between items-center text-xs">
                      <div className="space-y-0.5 max-w-[280px]">
                        <p className="font-bold text-zinc-800">{item.name}</p>
                        <p className="text-[10px] text-zinc-400 font-mono uppercase tracking-wide">{item.sku}</p>
                        <p className="text-[10px] text-zinc-500 font-medium">
                          Calculated Rate Basis: <span className="text-zinc-800 font-mono font-bold">{item.rateLabel}</span>
                        </p>
                      </div>
                      <div className="text-right">
                        <p className="font-mono font-bold text-zinc-900">
                          ₱{item.revenue.toLocaleString()}
                        </p>
                        <p className="text-[10px] text-zinc-500 font-semibold">
                          {item.isFlatFee 
                            ? `${item.quantity} permit(s) @ flat fee` 
                            : `${item.quantity} units × ${item.days} days ${item.isHourly ? ' (24h rate)' : ''}`}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Summary Statement */}
              <div className="border-t border-zinc-200 pt-4 flex justify-between items-center">
                <div>
                  <span className="text-[10px] font-black text-zinc-400 uppercase tracking-widest block">Statement Status</span>
                  <span className={`inline-block px-2 py-0.5 text-[9px] font-black uppercase tracking-widest mt-1 ${
                    selectedTxDetail.status === 'Returned' 
                      ? 'bg-emerald-50 text-emerald-700 border border-emerald-200' 
                      : 'bg-amber-50 text-amber-700 border border-amber-200'
                  }`}>
                    {selectedTxDetail.status}
                  </span>
                </div>
                <div className="text-right">
                  <span className="text-[10px] font-black text-zinc-400 uppercase tracking-widest block">Total Computed Invoice</span>
                  <span className="text-xl font-black font-mono text-emerald-800 mt-1 block">
                    ₱{selectedTxDetail.totalRevenue.toLocaleString()}
                  </span>
                </div>
              </div>
            </div>

            {/* Footer */}
            <div className="border-t border-zinc-200 p-4 bg-zinc-50/50 flex justify-end">
              <button
                onClick={() => setSelectedTxDetail(null)}
                className="px-4 py-1.5 text-xs font-bold uppercase tracking-widest text-zinc-800 bg-white border border-zinc-300 hover:bg-zinc-100 transition-colors cursor-pointer"
              >
                Close Statement
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
